var HERO_INFO = {
    "H10000": {
        "id": "H10000",
        "name" : "斯温",
        "reputation": "流浪剑客",
        "attack": 4,
        "def": 1,
        "health": 11,
        "maxHealth": 11,
        "anger": 0,
        "maxAnger": 4,
        "cardNum": 0,
        "maxCardNum": 4,
        "herodec":"守夜骑士团巴拉巴拉",
        "img":"10054_psd.png",
        "camp":"radiant",
        "campText":$.Localize("#RADIANT_TEAM_TEXT"),
        "ability": [
            {
                "id": "SK10000",
                "skillName": "风暴之锤",
                "instructions": "1.选择技能。 2.选择一名英雄。 3.点击确认按钮",
                "desc": "指定一名英雄。对其释放后其获得【晕眩】状态。",
                "tips": ["stun"],
                "cost": 1,
                "type": "AS",
                "assignNum": 1,
                "filterCardType": [],
                "damage": 2,
                "damageType": "D",
                "scene": "SELF",
                "stage": ["playing"],
                "cd": 1,
                "isUse": false,
                "effect": function(self, taget, info){

                }
            },
            {
                "id": "SK10001",
                "skillName": "巨力挥舞",
                "instructions": "1.当打出【攻击】时，可以选择是否使用该技能。",
                "desc": "你的【攻击】伤害会被分裂到目标左右的英雄，分裂伤害为 英雄攻击力 / 2 - 1的 【物理伤害】",
                "tips": ["division"],
                "cost": 1,
                "type": "ASCMS",
                "assignNum": 3,
                "filterCardType": ["Attack"],
                "damage": "CALC",
                "damageType": "D",
                "scene": "ALL",
                "stage": ["playing","dPlaying"],
                "cd": 0,
                "isUse": true,
                "effect": function(self, taget, info){

                }
            },
            {
                "id": "SK10002",
                "skillName": "神之力量",
                "instructions": "1.点击技能按钮。",
                "desc": "你的【攻击】将会翻倍，持续2回合。",
                "tips": [],
                "cost": 4,
                "type": "RA",
                "assignNum": 0,
                "filterCardType": [],
                "damage": "",
                "damageType": "D",
                "scene": "SELF",
                "stage": ["playing"],
                "cd": 2,
                "isUse": true,
                "effect": function(self, taget, info){

                }
            }
        ]
    },
    "H10001": {
        "id": "H10001",
        "name" : "崔希丝",
        "reputation": "卓尔游侠",
        "attack": 3,
        "def": 0,
        "health": 10,
        "maxHealth": 10,
        "anger": 0,
        "maxAnger": 3,
        "cardNum": 0,
        "maxCardNum": 4,
        "herodec":"巴拉巴拉",
        "img":"10032_psd.png",
        "camp":"dire",
        "campText":$.Localize("#DIRE_TEAM_TEXT"),
        "ability": [
            {
                "id": "SK10003",
                "skillName": "精度光环",
                "instructions": "1.当打出【攻击】时 2.选择是否触发该技能",
                "desc": "场上任何人打出【攻击】时，该攻击力伤害增加 + 1【物理伤害】。且伤害至少为 1【物理伤害】",
                "cost": 1,
                "type": "ASCMS",
                "assignNum": 1,
                "filterCardType": ["Attack"],
                "damage": "CALC",
                "damageType": "D",
                "scene": "ALL",
                "stage": ["playing","dPlaying"],
                "cd": 0,
                "isUse": true,
                "effect": function(self, taget, info){

                }
            },
            {
                "id": "SK10004",
                "skillName": "射手天赋",
                "instructions": "1.当打出【攻击】时。 2.选择是否触发该技能判定",
                "desc": "若判定成功，你的【攻击】将无视护甲且不能够被闪避",
                "tips": [],
                "cost": 1,
                "type": "RA",
                "assignNum": 0,
                "filterCardType": [],
                "damage": 0,
                "damageType": "D",
                "scene": "ALL",
                "stage": ["playing","dPlaying"],
                "cd": 1,
                "isUse": true,
                "effect": function(self, taget, info){

                }
            },
            {
                "id": "SK10005",
                "skillName": "狂风",
                "instructions": "1.选择技能 2.选择1-2个英雄",
                "desc": "选中1-2个英雄，令其无法释放主动技能。和打出非【基本牌】",
                "tips": [],
                "cost": 3,
                "type": "AS",
                "assignNum": 0,
                "filterCardType": [],
                "damage": 0,
                "damageType": "D",
                "scene": "ALL",
                "stage": ["playing","dPlaying"],
                "cd": 1,
                "isUse": true,
                "effect": function(self, taget, info){

                }
            }
        ]
    },
    "H10002": {
        "id": "H10002",
        "name" : "瑞克斯",
        "reputation": "豺狼人叛军首领",
        "attack": 3,
        "def": 0,
        "health": 9,
        "maxHealth": 9,
        "anger": 0,
        "maxAnger": 4,
        "cardNum": 0,
        "maxCardNum": 4,
        "herodec":"巴拉巴拉",
        "img":"10026_psd.png",
        "camp":"neutral",
        "campText":$.Localize("#NEUTRAL_TEAM_TEXT"),
        "ability": [
            {
                "id": "SK10006",
                "skillName": "韬晦",
                "instructions": "",
                "desc": "",
                "cost": 1,
                "type": "SD",
                "assignNum": 1,
                "filterCardType": [],
                "damage": "",
                "damageType": "D",
                "scene": "ALL",
                "stage": ["all"],
                "cd": 0,
                "isUse": true,
                "effect": function(self, taget, info){

                }
            },
            {
                "id": "SK10007",
                "skillName": "快速部署",
                "instructions": "1.点击技能",
                "desc": "当任何玩家开始阶段时，你没有任何手牌时可以触发该技能。立即进入你的回合选择场上0-3名玩家各摸3张手牌。每当进入你的摸牌阶段时都会额外摸1张牌。",
                "tips": [],
                "cost": 2,
                "type": "RA",
                "assignNum": 0,
                "filterCardType": [],
                "damage": 0,
                "damageType": "D",
                "scene": "ALL",
                "stage": ["start"],
                "cd": 99,
                "isUse": true,
                "effect": function(self, taget, info){

                }
            }
        ]
    },
    "H10003": {
        "id": "H10003",
        "name" : "海民",
        "reputation": "巨牙海民",
        "attack": 4,
        "def": 0,
        "health": 13,
        "maxHealth": 13,
        "anger": 0,
        "maxAnger": 4,
        "cardNum": 0,
        "maxCardNum": 4,
        "herodec":"巴拉巴拉",
        "img":"10674_psd.png",
        "camp":"neutral",
        "campText":$.Localize("#NEUTRAL_TEAM_TEXT"),
        "ability": [
            {
                "id": "SK10008",
                "skillName": "寒冰碎片",
                "instructions": "啦啦啦啦啦啦啦啦绿绿绿绿绿绿绿绿",
                "desc": "啦啦啦啦啦啦啦啦绿绿绿绿绿绿绿绿",
                "cost": 1,
                "type": "SD",
                "assignNum": 1,
                "filterCardType": [],
                "damage": "",
                "damageType": "D",
                "scene": "ALL",
                "stage": ["all"],
                "cd": 0,
                "isUse": true,
                "effect": function(self, taget, info){

                }
            },
            {
                "id": "SK10009",
                "skillName": "海象神拳",
                "instructions": "1.点击技能",
                "desc": "啦啦啦啦啦啦",
                "tips": [],
                "cost": 2,
                "type": "RA",
                "assignNum": 0,
                "filterCardType": [],
                "damage": 0,
                "damageType": "D",
                "scene": "ALL",
                "stage": ["start"],
                "cd": 99,
                "isUse": true,
                "effect": function(self, taget, info){

                }
            }
        ]
    },
    "H10004": {
        "id": "H10004",
        "name" : "Viper",
        "reputation": "冥界亚龙",
        "attack": 3,
        "def": 1,
        "health": 10,
        "maxHealth": 10,
        "anger": 0,
        "maxAnger": 4,
        "cardNum": 0,
        "maxCardNum": 4,
        "herodec":"巴拉巴拉",
        "img":"10028_psd.png",
        "camp":"dire",
        "campText":$.Localize("#DIRE_TEAM_TEXT"),
        "ability": []
    },
    "H10005": {
        "id": "H10005",
        "name" : "艾斯瑞安",
        "reputation": "巫妖",
        "attack": 2,
        "def": 0,
        "health": 9,
        "maxHealth": 9,
        "anger": 0,
        "maxAnger": 5,
        "cardNum": 0,
        "maxCardNum": 4,
        "herodec":"巴拉巴拉",
        "img":"10038_psd.png",
        "camp":"dire",
        "campText":$.Localize("#DIRE_TEAM_TEXT"),
        "ability": []
    },
    "H10006": {
        "id": "H10006",
        "name" : "莉莱",
        "reputation": "水晶室女",
        "attack": 2,
        "def": 0,
        "health": 9,
        "maxHealth": 9,
        "anger": 0,
        "maxAnger": 5,
        "cardNum": 0,
        "maxCardNum": 4,
        "herodec":"巴拉巴拉",
        "img":"10064_psd.png",
        "camp":"radiant",
        "campText":$.Localize("#RADIANT_TEAM_TEXT"),
        "ability": []
    },
    "H10007": {
        "id": "H10007",
        "name" : "达维安爵士",
        "reputation": "龙骑士",
        "attack": 4,
        "def": 1,
        "health": 11,
        "maxHealth": 11,
        "anger": 0,
        "maxAnger": 4,
        "cardNum": 0,
        "maxCardNum": 4,
        "herodec":"巴拉巴拉",
        "img":"10982_psd.png",
        "camp":"radiant",
        "campText":$.Localize("#RADIANT_TEAM_TEXT"),
        "ability": []
    },
    "H10008": {
        "id": "H10008",
        "name" : "莉娜",
        "reputation": "秀逗魔导士",
        "attack": 3,
        "def": 0,
        "health": 10,
        "maxHealth": 10,
        "anger": 0,
        "maxAnger": 6,
        "cardNum": 0,
        "maxCardNum": 4,
        "herodec":"巴拉巴拉",
        "img":"10811_psd.png",
        "camp":"neutral",
        "campText":$.Localize("#NEUTRAL_TEAM_TEXT"),
        "ability": []
    },
    "H10009": {
        "id": "H10009",
        "name" : "扎贡纳斯",
        "reputation": "天怒法师",
        "attack": 3,
        "def": 0,
        "health": 9,
        "maxHealth": 9,
        "anger": 0,
        "maxAnger": 6,
        "cardNum": 0,
        "maxCardNum": 4,
        "herodec":"巴拉巴拉",
        "img":"10062_psd.png",
        "camp":"radiant",
        "campText":$.Localize("#RADIANT_TEAM_TEXT"),
        "ability": []
    },
    "H10010": {
        "id": "H10010",
        "name" : "罗坦德吉利",
        "reputation": "瘟疫法师",
        "attack": 3,
        "def": 1,
        "health": 9,
        "maxHealth": 9,
        "anger": 0,
        "maxAnger": 4,
        "cardNum": 0,
        "maxCardNum": 4,
        "herodec":"巴拉巴拉",
        "img":"10059_psd.png",
        "camp":"dire",
        "campText":$.Localize("#DIRE_TEAM_TEXT"),
        "ability": []
    },
    "H10011": {
        "id": "H10011",
        "name" : "卡德尔",
        "reputation": "狙击手",
        "attack": 4,
        "def": 0,
        "health": 9,
        "maxHealth": 9,
        "anger": 0,
        "maxAnger": 3,
        "cardNum": 0,
        "maxCardNum": 4,
        "herodec":"巴拉巴拉",
        "img":"10050_psd.png",
        "camp":"radiant",
        "campText":$.Localize("#RADIANT_TEAM_TEXT"),
        "ability": []
    },
    "H10012": {
        "id": "H10012",
        "name" : "帕格纳",
        "reputation": "湮灭法师",
        "attack": 2,
        "def": 0,
        "health": 8,
        "maxHealth": 8,
        "anger": 0,
        "maxAnger": 5,
        "cardNum": 0,
        "maxCardNum": 4,
        "herodec":"巴拉巴拉",
        "img":"10048_psd.png",
        "camp":"dire",
        "campText":$.Localize("#DIRE_TEAM_TEXT"),
        "ability": []
    },
    "H10013": {
        "id": "H10013",
        "name" : "亚巴顿",
        "reputation": "无光骑士",
        "attack": 2,
        "def": 0,
        "health": 8,
        "maxHealth": 8,
        "anger": 0,
        "maxAnger": 5,
        "cardNum": 0,
        "maxCardNum": 4,
        "herodec":"巴拉巴拉",
        "img":"10016_psd.png",
        "camp":"dire",
        "campText":$.Localize("#DIRE_TEAM_TEXT"),
        "ability": []
    },
    "H10014": {
        "id": "H10014",
        "name" : "基弗·灭树者",
        "reputation": "食人魔拳手",
        "attack": 4,
        "def": 1,
        "health": 14,
        "maxHealth": 14,
        "anger": 0,
        "maxAnger": 2,
        "cardNum": 0,
        "maxCardNum": 4,
        "herodec":"巴拉巴拉",
        "img":"11003_psd.png",
        "camp":"neutral",
        "campText":$.Localize("#NEUTRAL_TEAM_TEXT"),
        "ability": []
    }
}